<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>8</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>BSFixes</RootNamespace>
    <AssemblyName>BSFixes</AssemblyName>
    <BeatSaberDir Condition="'$(BeatSaberDir)' == ''">D:\BSManager\BSInstances\1.45.1</BeatSaberDir>
    <OutputPath>bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony" HintPath="$(BeatSaberDir)\Libs\0Harmony.dll" Private="false" />
    <Reference Include="IPA.Loader">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\IPA.Loader.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <PackageReference Include="BeatSaberModdingTools.Tasks" Version="1.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="manifest.json" />
  </ItemGroup>
</Project>
